# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/fast/unreal/opt/unreal-engine

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	bh3d-Android-DebugGame  \
	bh3d-Android-Development  \
	bh3d-Android-Shipping  \
	bh3d-Linux-DebugGame  \
	bh3d-Linux-Development  \
	bh3d-Linux-Shipping  \
	bh3d-LinuxArm64-DebugGame  \
	bh3d-LinuxArm64-Development  \
	bh3d-LinuxArm64-Shipping  \
	bh3d \
	bh3dEditor-Linux-DebugGame  \
	bh3dEditor-Linux-Development  \
	bh3dEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend bh3dEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug bh3dEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

bh3d-Android-DebugGame:
	 $(BUILD) bh3d Android DebugGame  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d-Android-Development:
	 $(BUILD) bh3d Android Development  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d-Android-Shipping:
	 $(BUILD) bh3d Android Shipping  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d-Linux-DebugGame:
	 $(BUILD) bh3d Linux DebugGame  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d-Linux-Development:
	 $(BUILD) bh3d Linux Development  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d-Linux-Shipping:
	 $(BUILD) bh3d Linux Shipping  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d-LinuxArm64-DebugGame:
	 $(BUILD) bh3d LinuxArm64 DebugGame  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d-LinuxArm64-Development:
	 $(BUILD) bh3d LinuxArm64 Development  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d-LinuxArm64-Shipping:
	 $(BUILD) bh3d LinuxArm64 Shipping  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3d: bh3d-Linux-Development

bh3dEditor-Linux-DebugGame:
	 $(BUILD) bh3dEditor Linux DebugGame  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3dEditor-Linux-Development:
	 $(BUILD) bh3dEditor Linux Development  -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" $(ARGS)

bh3dEditor: bh3dEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/MMUStuff/fyp/bh3d/bh3d.uproject" -Game 

.PHONY: $(TARGETS)
