# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/fast/unreal/opt/unreal-engine

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	bh3d_fyp2-Android-DebugGame  \
	bh3d_fyp2-Android-Development  \
	bh3d_fyp2-Android-Shipping  \
	bh3d_fyp2-Linux-DebugGame  \
	bh3d_fyp2-Linux-Development  \
	bh3d_fyp2-Linux-Shipping  \
	bh3d_fyp2-LinuxArm64-DebugGame  \
	bh3d_fyp2-LinuxArm64-Development  \
	bh3d_fyp2-LinuxArm64-Shipping  \
	bh3d_fyp2 \
	bh3d_fyp2Editor-Linux-DebugGame  \
	bh3d_fyp2Editor-Linux-Development  \
	bh3d_fyp2Editor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend bh3d_fyp2Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug bh3d_fyp2Editor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

bh3d_fyp2-Android-DebugGame:
	 $(BUILD) bh3d_fyp2 Android DebugGame  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2-Android-Development:
	 $(BUILD) bh3d_fyp2 Android Development  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2-Android-Shipping:
	 $(BUILD) bh3d_fyp2 Android Shipping  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2-Linux-DebugGame:
	 $(BUILD) bh3d_fyp2 Linux DebugGame  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2-Linux-Development:
	 $(BUILD) bh3d_fyp2 Linux Development  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2-Linux-Shipping:
	 $(BUILD) bh3d_fyp2 Linux Shipping  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2-LinuxArm64-DebugGame:
	 $(BUILD) bh3d_fyp2 LinuxArm64 DebugGame  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2-LinuxArm64-Development:
	 $(BUILD) bh3d_fyp2 LinuxArm64 Development  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2-LinuxArm64-Shipping:
	 $(BUILD) bh3d_fyp2 LinuxArm64 Shipping  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2: bh3d_fyp2-Linux-Development

bh3d_fyp2Editor-Linux-DebugGame:
	 $(BUILD) bh3d_fyp2Editor Linux DebugGame  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2Editor-Linux-Development:
	 $(BUILD) bh3d_fyp2Editor Linux Development  -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" $(ARGS)

bh3d_fyp2Editor: bh3d_fyp2Editor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/MMUStuff/fyp2/bh3d-fyp2/bh3d_fyp2.uproject" -Game 

.PHONY: $(TARGETS)
