#pragma once

#include "CoreMinimal.h"
#include "BulletMotionParams.h"
#include "ESpreadMode.h"
#include "BeamDefinition.generated.h"

/**
 * FBeamDefinition
 *
 * Describes one beam within a UFirePattern.
 *
 * ── Bullet spread ─────────────────────────────────────────────────────────
 *
 * Spread is always expressed as a TArray<FVector> of local directions at
 * runtime. SpreadMode selects how that array is generated:
 *
 *   Rim    → evenly spaced on the cone rim   (hollow)
 *   Filled → Fibonacci spiral inside the cap (solid)
 *   Cross  → rim aligned to local axes
 *   Custom → you supply CustomSpreadDirections directly
 *
 * All directions — whether generated by a preset or provided manually —
 * use the same beam-local frame:
 *
 *   X = forward (along beam axis). (1,0,0) = no deflection.
 *   Y = cone right (perpendicular to beam, computed at spawn time).
 *   Z = cone up   (perpendicular to beam and right).
 *
 * The spawner transforms them to world space as:
 *   worldDir = BeamDir*local.X + ConeRight*local.Y + ConeUp*local.Z
 *
 * ── Indexing ─────────────────────────────────────────────────────────────
 *
 * BeamOverrides in UFirePattern are indexed linearly:
 *   index = elevationStep * BeamCount + azimuthStep
 */
USTRUCT(BlueprintType)
struct FBeamDefinition
{
    GENERATED_BODY()

    // ── Placement ─────────────────────────────────────────────────────────

    /**
     * Additional elevation offset for this beam, in degrees, applied on top
     * of the ring's elevation set in UFirePattern.
     *
     * Positive = tilts the beam further upward.
     * Negative = tilts the beam further downward.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Placement",
              meta=(ClampMin="-90", ClampMax="90"))
    float ElevationOffset = 0.f;

    // ── Spread ────────────────────────────────────────────────────────────

    /**
     * How bullets are distributed within this beam's cone.
     * Presets (Rim, Filled, Cross) generate their direction arrays from
     * BulletsPerBeam, ConeHalfAngle, and ConeRollOffset.
     * Custom uses CustomSpreadDirections directly.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Spread")
    ESpreadMode SpreadMode = ESpreadMode::Rim;

    /** How many bullets fire in this beam per volley. Used by presets. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Spread",
              meta=(ClampMin="1",
                    EditCondition="SpreadMode != ESpreadMode::Custom"))
    int32 BulletsPerBeam = 1;

    /**
     * Half-angle of the spread cone, in degrees. Used by presets.
     *
     *   0  = no spread, all bullets travel along beam axis
     *   15 = bullets travel 15° away from axis
     *   90 = bullets travel perpendicular to the beam (disc)
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Spread",
              meta=(ClampMin="0", ClampMax="180",
                    EditCondition="SpreadMode != ESpreadMode::Custom"))
    float ConeHalfAngle = 0.f;

    /**
     * Rotational offset of the bullet arrangement around the beam axis, in degrees.
     * Used by Rim and Cross presets.
     *
     * Useful for interleaving two beams with the same BulletsPerBeam so
     * their bullets do not overlap: set ConeRollOffset = 360/(2*BulletsPerBeam)
     * on the second beam.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Spread",
              meta=(EditCondition="SpreadMode == ESpreadMode::Rim || SpreadMode == ESpreadMode::Cross"))
    float ConeRollOffset = 0.f;

    /**
     * User-supplied spread directions in beam-local space.
     * Only used when SpreadMode == Custom.
     *
     * Each entry is a unit vector in the beam-local frame:
     *   (1,0,0) = straight along beam axis (no deflection)
     *   (0,1,0) = 90° toward cone right
     *   (0,0,1) = 90° toward cone up
     *
     * You can populate this from UBulletSpreadLibrary functions and then
     * modify individual entries, or author the directions by hand.
     *
     * The number of entries determines how many bullets fire per volley.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Spread",
              meta=(EditCondition="SpreadMode == ESpreadMode::Custom"))
    TArray<FVector> CustomSpreadDirections;

    /**
     * Linear distance between bullet spawn positions along the beam direction, cm.
     * When > 0, bullets are staggered outward from the spawn origin.
     * Applied in order of the spread direction array (preset or custom).
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Spread")
    float SpacingBetweenBullets = 0.f;

    // ── Overrides ─────────────────────────────────────────────────────────

    /**
     * Override the bullet class for this beam only.
     * Leave null to inherit the pattern's DefaultBulletClass.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Overrides")
    TSubclassOf<AActor> BulletClassOverride;

    /** If true, MotionParamsOverride is used instead of the pattern's default. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Overrides")
    bool bOverrideMotionParams = false;

    /** Per-beam motion params. Only used when bOverrideMotionParams is true. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Beam|Overrides",
              meta=(EditCondition="bOverrideMotionParams"))
    FBulletMotionParams MotionParamsOverride;
};
